# -*- coding: utf-8 -*-
"""Ejercicio 04- Lab 01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rYrJRbE2a80cBsBgdeh8XwJKJl3raMsG
"""

!pip install chromadb
!pip install sentence-transformers

import chromadb
from chromadb.utils import embedding_functions

# Cliente persistente: los datos se guardan en disco
client = chromadb.PersistentClient(path='./sistema_cursos_db')

# Función de embeddings con sentence-transformers
embedding_fn = embedding_functions.SentenceTransformerEmbeddingFunction(
    model_name='all-MiniLM-L6-v2'
)

# Crear o recuperar la colección
collection = client.get_or_create_collection(
    name='cursos_ingenieria',
    embedding_function=embedding_fn,
    metadata={'hnsw:space': 'cosine'}
)

print(f'✅ Colección lista: {collection.name}')
print(f'📦 Documentos actuales: {collection.count()}')

cursos_data = [
    {
        'id': 'curso_001',
        'nombre': 'Cálculo Diferencial',
        'descripcion': (
            'Estudio de límites, derivadas y sus aplicaciones en ingeniería. '
            'Se analizan funciones de una variable y sus propiedades de continuidad. '
            'Incluye optimización de funciones y regla de la cadena aplicada a problemas reales.'
        ),
        'creditos': 4, 'semestre': 1, 'area': 'básica',
        'prerequisitos': 'Ninguno'
    },
    {
        'id': 'curso_002',
        'nombre': 'Álgebra Lineal',
        'descripcion': (
            'Estudio de vectores, matrices, determinantes y transformaciones lineales. '
            'Se cubren espacios vectoriales y sistemas de ecuaciones lineales. '
            'Fundamento esencial para machine learning, gráficos computacionales y redes neuronales.'
        ),
        'creditos': 4, 'semestre': 1, 'area': 'básica',
        'prerequisitos': 'Ninguno'
    },
    {
        'id': 'curso_003',
        'nombre': 'Programación Orientada a Objetos',
        'descripcion': (
            'Paradigma de programación basado en clases, objetos, herencia y polimorfismo. '
            'Se desarrollan aplicaciones en Python y Java aplicando patrones de diseño básicos. '
            'Incluye encapsulamiento, abstracción e interfaces para diseño modular de software.'
        ),
        'creditos': 3, 'semestre': 2, 'area': 'básica',
        'prerequisitos': 'Introducción a la Programación'
    },
    {
        'id': 'curso_004',
        'nombre': 'Estructuras de Datos',
        'descripcion': (
            'Estudio de listas enlazadas, pilas, colas, árboles y grafos. '
            'Se implementan algoritmos de búsqueda y ordenamiento eficientes. '
            'Análisis de complejidad temporal y espacial con notación Big-O.'
        ),
        'creditos': 4, 'semestre': 3, 'area': 'básica',
        'prerequisitos': 'Programación Orientada a Objetos'
    },
    {
        'id': 'curso_005',
        'nombre': 'Base de Datos I',
        'descripcion': (
            'Diseño de bases de datos relacionales usando el modelo entidad-relación. '
            'Se estudia SQL para consultas, inserciones, actualizaciones y eliminaciones. '
            'Normalización de tablas hasta tercera forma normal para evitar redundancia.'
        ),
        'creditos': 3, 'semestre': 3, 'area': 'básica',
        'prerequisitos': 'Estructuras de Datos'
    },
    {
        'id': 'curso_006',
        'nombre': 'Algoritmos y Complejidad',
        'descripcion': (
            'Diseño de algoritmos usando técnicas de divide y vencerás, programación dinámica y greedy. '
            'Se analiza la complejidad computacional y clases de problemas P y NP. '
            'Aplicaciones prácticas en optimización combinatoria y grafos.'
        ),
        'creditos': 4, 'semestre': 4, 'area': 'básica',
        'prerequisitos': 'Estructuras de Datos, Matemática Discreta'
    },
    {
        'id': 'curso_007',
        'nombre': 'Redes de Computadoras',
        'descripcion': (
            'Estudio del modelo OSI y TCP/IP para comunicación entre dispositivos. '
            'Se configuran protocolos de enrutamiento como OSPF y BGP en entornos simulados. '
            'Incluye seguridad básica de redes, firewalls y VPNs.'
        ),
        'creditos': 3, 'semestre': 4, 'area': 'básica',
        'prerequisitos': 'Sistemas Operativos'
    },
    {
        'id': 'curso_008',
        'nombre': 'Ingeniería de Software',
        'descripcion': (
            'Metodologías de desarrollo de software incluyendo Scrum, Kanban y cascada. '
            'Se aprende a levantar requerimientos, diseñar arquitecturas y gestionar proyectos. '
            'Incluye pruebas unitarias, integración continua y control de versiones con Git.'
        ),
        'creditos': 4, 'semestre': 5, 'area': 'especialidad',
        'prerequisitos': 'Programación Orientada a Objetos, Base de Datos I'
    },
    {
        'id': 'curso_009',
        'nombre': 'Inteligencia Artificial',
        'descripcion': (
            'Fundamentos de IA incluyendo búsqueda heurística, lógica y agentes inteligentes. '
            'Se implementan algoritmos como A*, minimax y redes bayesianas. '
            'Introducción al aprendizaje automático supervisado y no supervisado.'
        ),
        'creditos': 4, 'semestre': 6, 'area': 'especialidad',
        'prerequisitos': 'Algoritmos y Complejidad, Probabilidad y Estadística'
    },
    {
        'id': 'curso_010',
        'nombre': 'Machine Learning',
        'descripcion': (
            'Algoritmos de aprendizaje supervisado como regresión, SVM y árboles de decisión. '
            'Se estudian técnicas no supervisadas como clustering K-means y PCA. '
            'Evaluación de modelos con métricas como precisión, recall y F1-score usando scikit-learn.'
        ),
        'creditos': 4, 'semestre': 7, 'area': 'especialidad',
        'prerequisitos': 'Inteligencia Artificial, Álgebra Lineal'
    },
    {
        'id': 'curso_011',
        'nombre': 'Deep Learning',
        'descripcion': (
            'Redes neuronales profundas incluyendo CNN, RNN y transformers. '
            'Se implementan modelos con TensorFlow y PyTorch para visión y NLP. '
            'Técnicas de regularización, optimización y transfer learning en problemas reales.'
        ),
        'creditos': 4, 'semestre': 8, 'area': 'especialidad',
        'prerequisitos': 'Machine Learning, Cálculo Diferencial'
    },
    {
        'id': 'curso_012',
        'nombre': 'Base de Datos Avanzada',
        'descripcion': (
            'Bases de datos NoSQL incluyendo MongoDB, Redis y Cassandra. '
            'Se estudian bases de datos vectoriales como ChromaDB y Pinecone para IA generativa. '
            'Optimización de consultas, índices avanzados y arquitecturas distribuidas.'
        ),
        'creditos': 3, 'semestre': 6, 'area': 'especialidad',
        'prerequisitos': 'Base de Datos I'
    },
    {
        'id': 'curso_013',
        'nombre': 'Seguridad Informática',
        'descripcion': (
            'Principios de criptografía simétrica y asimétrica para protección de datos. '
            'Se estudian vulnerabilidades comunes como SQL injection, XSS y CSRF. '
            'Ethical hacking, análisis forense digital y normativas de seguridad ISO 27001.'
        ),
        'creditos': 3, 'semestre': 7, 'area': 'especialidad',
        'prerequisitos': 'Redes de Computadoras'
    },
    {
        'id': 'curso_014',
        'nombre': 'Desarrollo Web Full Stack',
        'descripcion': (
            'Desarrollo frontend con React y backend con Node.js y FastAPI. '
            'Se implementan APIs RESTful y GraphQL conectadas a bases de datos relacionales. '
            'Despliegue de aplicaciones en la nube con Docker, CI/CD y servicios AWS.'
        ),
        'creditos': 4, 'semestre': 5, 'area': 'especialidad',
        'prerequisitos': 'Base de Datos I, Programación Orientada a Objetos'
    },
    {
        'id': 'curso_015',
        'nombre': 'Computación en la Nube',
        'descripcion': (
            'Servicios cloud de AWS, Azure y GCP para infraestructura escalable. '
            'Se configuran máquinas virtuales, contenedores Docker y orquestación con Kubernetes. '
            'Arquitecturas serverless, microservicios y modelos de costos en la nube.'
        ),
        'creditos': 3, 'semestre': 8, 'area': 'especialidad',
        'prerequisitos': 'Redes de Computadoras, Ingeniería de Software'
        },
    {
        'id': 'curso_016',
        'nombre': 'Procesamiento de Lenguaje Natural',
        'descripcion': (
            'Técnicas de NLP incluyendo tokenización, embeddings y modelos de lenguaje. '
            'Se implementan sistemas de análisis de sentimientos, chatbots y traducción automática. '
            'Uso de transformers como BERT y GPT para tareas de comprensión y generación de texto.'
        ),
        'creditos': 4, 'semestre': 9, 'area': 'especialidad',
        'prerequisitos': 'Deep Learning'
    },
    {
        'id': 'curso_017',
        'nombre': 'Visión por Computadora',
        'descripcion': (
            'Procesamiento de imágenes digitales con filtros, detección de bordes y segmentación. '
            'Se implementan modelos de detección de objetos con YOLO y Faster R-CNN. '
            'Aplicaciones en reconocimiento facial, conducción autónoma y diagnóstico médico.'
        ),
        'creditos': 4, 'semestre': 9, 'area': 'especialidad',
        'prerequisitos': 'Deep Learning'
    },
    {
        'id': 'curso_018',
        'nombre': 'Ética en Tecnología e IA',
        'descripcion': (
            'Análisis de dilemas éticos en el desarrollo y uso de sistemas de inteligencia artificial. '
            'Se estudian sesgos algorítmicos, privacidad de datos y responsabilidad en IA. '
            'Marcos regulatorios como el AI Act de la Unión Europea y principios de IA responsable.'
        ),
        'creditos': 2, 'semestre': 8, 'area': 'electivo',
        'prerequisitos': 'Inteligencia Artificial'
    },
    {
        'id': 'curso_019',
        'nombre': 'Emprendimiento Tecnológico',
        'descripcion': (
            'Metodología Lean Startup para validar ideas de negocio tecnológico con MVPs. '
            'Se desarrollan modelos de negocio usando el Business Model Canvas. '
            'Pitch de inversión, captación de fondos y estrategias de crecimiento para startups tech.'
        ),
        'creditos': 2, 'semestre': 9, 'area': 'electivo',
        'prerequisitos': 'Ninguno'
    },
    {
        'id': 'curso_020',
        'nombre': 'Proyecto de Tesis I',
        'descripcion': (
            'Formulación del problema de investigación y estado del arte en sistemas de información. '
            'Se desarrolla la metodología de investigación y el plan de trabajo del proyecto final. '
            'Incluye escritura académica, gestión de referencias y presentación de avances.'
        ),
        'creditos': 4, 'semestre': 10, 'area': 'especialidad',
        'prerequisitos': 'Haber aprobado 160 créditos'
    },
]

print(f'✅ {len(cursos_data)} cursos definidos correctamente')

if collection.count() == 0:
    print('🆕 Primera ejecución: insertando cursos...')

    documentos = [
        f"{c['nombre']}. {c['descripcion']} Prerequisitos: {c['prerequisitos']}"
        for c in cursos_data
    ]

    metadatos = [
        {
            'nombre': c['nombre'],
            'creditos': c['creditos'],
            'semestre': c['semestre'],
            'area': c['area'],
            'prerequisitos': c['prerequisitos']
        }
        for c in cursos_data
    ]

    ids = [c['id'] for c in cursos_data]

    collection.add(
        documents=documentos,
        metadatas=metadatos,
        ids=ids
    )
    print(f'✅ {collection.count()} cursos insertados exitosamente')

else:
    print(f'✅ Base de datos ya existe con {collection.count()} cursos. No se reinsertan.')

def recomendar_cursos(intereses_alumno: str, semestre_actual: int, top_k: int = 5):
    """
    Recomienda cursos según los intereses del alumno.
    Filtra cursos hasta el semestre actual del alumno.

    Args:
        intereses_alumno: texto libre con los intereses
        semestre_actual: semestre en el que está el alumno (1-10)
        top_k: número de recomendaciones a retornar

    Returns:
        dict con documentos, metadatos y distancias
    """
    resultados = collection.query(
        query_texts=[intereses_alumno],
        n_results=top_k,
        where={'semestre': {'$lte': semestre_actual}},
        include=['documents', 'distances', 'metadatas']
    )

    print(f"\n🎯 Recomendaciones para: '{intereses_alumno}' (Semestre actual: {semestre_actual})")
    print('=' * 65)

    for i, (doc, dist, meta) in enumerate(zip(
        resultados['documents'][0],
        resultados['distances'][0],
        resultados['metadatas'][0]
    ), start=1):
        similitud = 1 - dist
        print(f"\n  #{i} {meta['nombre']} | Similitud: {similitud:.4f}")
        print(f"     Semestre: {meta['semestre']} | Área: {meta['area']} | Créditos: {meta['creditos']}")
        print(f"     {doc[:100]}...")

    return resultados


def cursos_similares(nombre_curso: str, n: int = 3):
    """
    Dado el nombre de un curso, encuentra los N cursos más similares temáticamente.

    Args:
        nombre_curso: nombre exacto o aproximado del curso
        n: número de cursos similares a retornar

    Returns:
        dict con los cursos similares
    """
    # Buscar el curso por nombre en metadatos
    todos = collection.get(include=['documents', 'metadatas'])
    curso_doc = None
    curso_id = None

    for i, meta in enumerate(todos['metadatas']):
        if nombre_curso.lower() in meta['nombre'].lower():
            curso_doc = todos['documents'][i]
            curso_id = todos['ids'][i]
            break

    if not curso_doc:
        print(f"❌ No se encontró el curso: '{nombre_curso}'")
        return None

    # Usar el texto del curso como query, pedir n+1 para excluir el mismo
    resultados = collection.query(
        query_texts=[curso_doc],
        n_results=n + 1,
        include=['documents', 'distances', 'metadatas', 'ids']
    )

    print(f"\n🔍 Cursos similares a: '{nombre_curso}'")
    print('=' * 65)

    count = 0
    for doc, dist, meta, rid in zip(
        resultados['documents'][0],
        resultados['distances'][0],
        resultados['metadatas'][0],
        resultados['ids'][0]
    ):
        if rid == curso_id:  # Excluir el curso original
            continue
        similitud = 1 - dist
        print(f"\n  📘 {meta['nombre']} | Similitud: {similitud:.4f}")
        print(f"     Semestre: {meta['semestre']} | Área: {meta['area']}")
        print(f"     {doc[:100]}...")
        count += 1
        if count == n:
            break

    return resultados


def buscar_por_perfil(habilidades_lista: list, area: str = 'especialidad'):
    """
    Busca cursos que coincidan con un perfil de habilidades en un área específica.

    Args:
        habilidades_lista: lista de habilidades o tecnologías de interés
        area: área del curso ('básica', 'especialidad', 'electivo')

    Returns:
        dict con los cursos encontrados
    """
    query_text = ', '.join(habilidades_lista)

    resultados = collection.query(
        query_texts=[query_text],
        n_results=5,
        where={'area': {'$eq': area}},
        include=['documents', 'distances', 'metadatas']
    )

    print(f"\n🧑‍💻 Perfil buscado: {habilidades_lista}")
    print(f"   Área filtrada: {area}")
    print('=' * 65)

    for i, (doc, dist, meta) in enumerate(zip(
        resultados['documents'][0],
        resultados['distances'][0],
        resultados['metadatas'][0]
    ), start=1):
        similitud = 1 - dist
        print(f"\n  #{i} {meta['nombre']} | Similitud: {similitud:.4f}")
        print(f"     Semestre: {meta['semestre']} | Créditos: {meta['creditos']}")
        print(f"     Prerequisitos: {meta['prerequisitos']}")

    return resultados

print('✅ Las 3 funciones están listas')

def menu():
    """Interfaz de línea de comandos para el sistema de recomendación."""

    while True:
        print("\n" + "=" * 55)
        print("   🎓 SISTEMA DE RECOMENDACIÓN DE CURSOS - UNIV.")
        print("=" * 55)
        print("  1. Recomendar cursos según mis intereses")
        print("  2. Ver cursos similares a uno dado")
        print("  3. Buscar cursos por perfil de habilidades")
        print("  4. Salir")
        print("=" * 55)

        opcion = input("  Selecciona una opción (1-4): ").strip()

        if opcion == '1':
            intereses = input("\n  ¿Cuáles son tus intereses? (ej: inteligencia artificial, datos): ")
            try:
                semestre = int(input("  ¿En qué semestre estás? (1-10): "))
                if not 1 <= semestre <= 10:
                    print("  ⚠️ El semestre debe estar entre 1 y 10.")
                    continue
                top_k = int(input("  ¿Cuántas recomendaciones quieres? (default 5): ") or 5)
                recomendar_cursos(intereses, semestre, top_k)
            except ValueError:
                print("  ⚠️ Por favor ingresa un número válido.")

        elif opcion == '2':
            nombre = input("\n  Escribe el nombre del curso (ej: Machine Learning): ")
            try:
                n = int(input("  ¿Cuántos similares quieres ver? (default 3): ") or 3)
                cursos_similares(nombre, n)
            except ValueError:
                print("  ⚠️ Por favor ingresa un número válido.")

        elif opcion == '3':
            habilidades_input = input("\n  Lista tus habilidades separadas por coma\n  (ej: Python, redes neuronales, SQL): ")
            habilidades = [h.strip() for h in habilidades_input.split(',')]
            print("  Áreas disponibles: básica | especialidad | electivo")
            area = input("  ¿Qué área te interesa? (default: especialidad): ").strip() or 'especialidad'
            buscar_por_perfil(habilidades, area)

        elif opcion == '4':
            print("\n  👋 ¡Hasta luego!\n")
            break

        else:
            print("  ⚠️ Opción no válida. Ingresa 1, 2, 3 o 4.")

# Ejecutar el menú
menu()